version: 2.1

executors:
  smartnats-executor:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/app

jobs:
  build:
    executor: smartnats-executor
    steps:
      - checkout

      - run:
          name: Deploy Over SSH
          command: |
            echo "Build $ENV_MODE"
  deploy:
    executor: smartnats-executor
    steps:
      - checkout

      - run:
          name: Deploy Over SSH
          command: |
            echo "Deploy $ENV_MODE"

workflows:
  version: 2

  production:
    jobs:
      - build:
          context: circleci-test-prod
          filters:
             branches:
               only:
                 - master
      - deploy:
          context: circleci-test-prod
          requires:
            - build

  qa1:
    jobs:
      - build:
          context: circleci-test-qa1
          filters:
             branches:
               only:
                 - develop
      - deploy:
          context: circleci-test-prod
          requires:
            - build
