version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/app
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - "e5:1d:30:37:ac:f0:26:c4:45:32:67:18:33:ec:54:dc"

      - run: node ./index.js

      - persist_to_workspace:
          root: /
          paths:
            - index.js
  deploy:
    machine:
        image: ubuntu-1604:201903-01
    working_directory: ~/app
    steps:
      - run:
          name: List
          command: |
            ls .

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

