version: 2.1

executors:
  smartnats-executor:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/app

jobs:
  build:
    executor: smartnats-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: node ./index.js

      - persist_to_workspace:
          root: ~/app
          paths:
            - index.js
  deploy:
    executor: smartnats-executor
    steps:
      - attach_workspace:
          at: ~/app/images
      - run:
          name: List
          command: |
            ls ./images

      - add_ssh_keys:
          fingerprints:
            - "e5:1d:30:37:ac:f0:26:c4:45:32:67:18:33:ec:54:dc"

      - run:
          name: Deploy Over SSH
          command: |
            bash ./deploy-ssh.sh images

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

